### ISSUE TITLE
by any chance: is this app working yet? Test possible on NC20?

### ISSUE THREAD

**Issue by aheider** [mziech/nextcloud-calendar-news#1]
Dear mziech,
is this app working yet? 
can I test this on an NC20 install?

Sadly I am no developer, but I can try to test the app and debug it...

Yours.

**Comment by mziech** [comment]
Hi @aheider ,

well it was working for me last Friday on Nextcloud 20.

While sending the newsletter is working pretty smoothly, the configuration UI is a bit outdated. Therefore, and due to the absence of test, I refrained from going through the hoops for a Nextcloud App Store release so.

Since installation is a bit more difficult without the app store, I added short guide to the README and a release-build now.

Hope that helps!

**Comment by aheider** [comment]
Great, thanks!
I tried it and it works for me.
However, in what format do I fill thos fields:
![grafik](https://user-images.githubusercontent.com/6790802/116010712-fbe22c00-a620-11eb-896c-8d7e1285572d.png)

That is, for time to first entry, time to last entry, format for first/second row, and regular expression for description?

For the time interval I tried "1", "1 day", "1 d", "1 Tag". But that did not work...

Thank you so much.

**Comment by mziech** [comment]
Cool, glad that it works!

The timestamps need to be specified in ISO "period" format (not really obvious bus it was the easiest one to parse in the backend), e.g. `P30D` for 30 days.

Shell-like `${...}` placeholders are used for the format rows per appointment.

Possible placeholders are:
- `${startDate}` - the start day of the event
- `${endDate}` - the end day of the event
- `${dateTimeRange}` - a data time range for the event, omitting the end date if it is the same day
- `${dateRange}` - a date range (without time) if the event spans multiple days, start date other wise
- `${summary}` - the title line of the event
- `${description}` - the complete description body of the event
- `${0} ... ${n}` - if the regular expression contains placeholders, they can be addressed by just their number
- `${item.XYZ}` - for a line in the description starting like `XYZ: something`, this would contain `something`
- `${*}` - outputs all known placeholders as JSON for debugging

Additionally filters can be applied to each placeholder value like `${...|filter1|filter2}`. The following filters are known:
 - `${...|badge}` will put each line of the value in square brackets
 - `${...|pipe}` will separate the lines of the value by a pipe `|`
 - `${...|slash}` will separate the lines of the value by a slash `/`
 - `${...|nl}` will separate the lines of the value by a newline
 - `${...|dash}` will separate the lines of the value by a newline and a dash `-`
 - `${...|dash2}` will separate the lines of the value by a newline and a double dash `--`
 - `${...|dash3}` will separate the lines of the value by a newline and a triple dash `---`

If a placeholder cannot be resolved, a fallback can be specified using the colon charater `:`, otherwise the value will be empty. E.g. `${a:b:c}` would output the value of `b` if `a` is undefined or `c` if `a` and `b` are undefined.

Example:
![image](https://user-images.githubusercontent.com/4292954/116011723-b1fc4480-a626-11eb-96c2-23da71f136fb.png)

**Comment by aheider** [comment]
works as advertised. Thanks!
